plugin:
  name: custom-data-type-gn250
  version: 1.5
  url: https://github.com/programmfabrik/fylr-plugin-custom-data-type-gn250
  displayname:
    de-DE: gn250-Verkn체pfung
    en-US: gn250-Referencing
  info:
    de-DE: Stellt Verkn체pfungen mit den geographischen Daten des Bundesamtes f체r Kartographie und Geod채sie her.
    en-US: Provides links to the geographic data of the Federal Agency for Cartography and Geodesy.
  server:
    api-version:
      require: 1
  l10n: l10n/customDataTypeGN250.csv
  webfrontend:
    url: customDataTypeGN250.js
    css: customDataTypeGN250.css
    
base_url_prefix: "webfrontend"
    
custom_types:
  gn250:
    mapping:
      conceptName:
        type: text
      conceptURI:
        type: text
      conceptAncestors:
        type: text
      conceptGeoJSON:
        type: geo_json
      facetTerm:
        type: text_l10n
    config:
      schema:
        - name: mapbox_api_key
          parameters:
            value:
              type: text
      mask:
        - name: editor_display
          parameters:
            value:
              type: select
              options: ["default", "condensed"]
    update:
      plugin_user:
        reference: system:root
      exec:
        service: "node"
        commands:
          - prog: "node"
            stdin:
              type: body
            stdout:
              type: body
            args:
              - type: "value"
                value: "%_exec.pluginDir%/updater/gn250Updater.js"
              - type: "value"
                value: "%info.json%"
      timeout: 60
      batch_size: 1
      expires_days: 1
      interval_base_config: update_interval_gn250.days
              
              
base_config:
  - name: update_interval_gn250
    group: update_custom_data_type
    parameters:
      days:
        type: int
        min: 0
        default: 0
        position: 0
      default_language:
        type: text
        default: 'de'
        position: 1